version: "3.1"
services:
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./secrets:/run/secrets
      - ./db-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: sut_db
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQLUSER_PW
    networks:
      - sutnet

  api:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    image: chrisferg/standuptimerserver:dev
    volumes:
      - ./secrets:/run/secrets
      - ./server:/usr/src/server
    ports:
      - 8083:8083
    secrets:
      - MYSQLUSER_PW
    links:
      - db:db
    depends_on:
      - db
    networks:
      - sutnet

  app:
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    image: chrisferg/standuptimerapp:dev
    volumes:
      - ./app/src:/usr/src/app/src
    ports:
      - 8080:8080
    links:
      - api:api
    depends_on:
      - api
    networks:
      - sutnet

secrets:
  MYSQLUSER_PW:
    file: ./secrets/MYSQLUSER_PW

networks:
  sutnet:
