version: "3.1"
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: sut_db
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQLUSER_PW
    secrets:
      - MYSQLUSER_PW
    networks:
      - sutnet

  api:
    image: chrisferg/standuptimerserver:latest
    ports:
      - 8083:8083
    secrets:
      - MYSQLUSER_PW
    depends_on:
      - db
    networks:
      - sutnet

  app:
    image: chrisferg/standuptimerapp:latest
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - sutnet

secrets:
  MYSQLUSER_PW:
    external: true

networks:
  sutnet:
